#title in header
title: "Aurelio Florez"

#main info
#owner
owner: "I am Aurelio Florez"
email: mail@aurelioflorez.com
info: "A Computer Science student in Miami originaly from üá™üá∏"  
pronouns: "he/him"
#description
desc: "My dream job would be building recommendation algorithms at large scale. I love the intricacy of monitoring these systems and I am a fan of efficiency and scalability." 
desc2: "For now most of my free time is spent tinkering my linux rice, building keyboards or brewing coffee."

#menu
menu:
  Works: /archives
  Resume: /Aurelio-Florez-resume.pdf

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: d3869b

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Miami
  #placelink: https://en.wikipedia.org/wiki/Miami
github: https://github.com/aureliusf
linkedin: https://linkedin.com/in/aurelio-florez-621560221
twitter: https://twitter.com/aurelioflorez
  #instagram: https://instagram.com/aurelioflorez
  #stackoverflow: https://stackoverflow.com/story/tobiasreithmeier

# Misc
nanobar: /js/nanobar.min.js
switch_light: ‚òÄÔ∏è
switch_dark: üåë

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
  #disqus_shortname: https-adisaktijrs-github-io
